# Generated by Django 5.2.6 on 2025-09-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactos',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='contactos',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='contactos',
            name='precio',
        ),
        migrations.AddField(
            model_name='contactos',
            name='correo',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactos',
            name='direccion',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactos',
            name='telefono',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
