# Generated by Django 5.2.6 on 2025-11-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_remove_contactos_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='contactos',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='contactos.etiqueta'),
        ),
    ]
