# Generated by Django 5.2.6 on 2025-11-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_etiqueta_contactos_etiquetas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactos',
            name='etiquetas',
        ),
    ]
