# Generated by Django 5.2.8 on 2025-11-07 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactos", "0004_remove_contactos_etiquetas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactos",
            name="telefono",
            field=models.CharField(
                help_text="Número con 10-15 dígitos, puede incluir +",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_telefono",
                        message="El teléfono debe contener solo números y tener entre 10 y 15 dígitos. Puede iniciar con +.",
                        regex="^\\+?\\d{10,15}$",
                    )
                ],
            ),
        ),
    ]
