# Generated by Django 5.2.6 on 2025-11-25 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0005_alter_contactos_telefono'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etiqueta',
        ),
    ]
